### ISSUE TITLE
Segurización y estabilización del entorno datos.gob.ar

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/portal_datos.gob.ar#5]
* [x] Automatizar (o simplificar) backups
* [x] Reinicio automático del proceso docker
* [x] Instalacion de dependencias
* [x] Instalacion de la aplicacion
* [x] Rotacion de logs
* [x] Rotacion de backups

- [ ] Ver como migrar del actual datos.gob.ar a la nueva version con ansible

**Comment by lalo73** [comment]
Ver la implementación acá: https://github.com/datosgobar/portal-deploy
